
* Overview

This repository contains a Python implementation of the Weighted
Ensemble (WE) method for sampling rare events from probability
distributions generated by arbitrary Markov processes.

* References
  - [[http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2830257/][Huber and Kim. Biophys. J. 70, 97 (1996).]]
  - [[http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2830257/][Zhang, Jasnow and Zuckerman.  J Chem Phys. 2010 February 7; 132(5): 054107.]] 
  - [[http://scitation.aip.org/content/aip/journal/jcp/139/11/10.1063/1.4821167][Donovan, RM et al.  J. Chem. Phys. 139, 115105 (2013)]]
  See also:

  - [[chong.chem.pitt.edu/WESTPA/we-overview.pdf‎][Zuckerman, DM.  Overview of Weighted Ensemble Simulation.]]

  for an overview.

* Installation

To put the =we= library where Python can find it, clone the repository
and execute the following from the top-level directory:

: sudo python setup.py install

* Acknowledgements

  Thanks to Rory Donovan for introducing me to the algorithm and for
  helpful comments on implementation.

** A note on the preferred nomenclature

   WE is a powerful yet very general sampling method, hence "the royal
   WE".  You know, the editorial...
